name: tstrippy
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - astropy>=7.0
  - pyyaml
  - hdf5
  - pytest
  
  # Runtime/build deps
  - build
  - meson
  - meson-python
  - ninja  

  # compiler toolchain (important for Agama + OpenMP on macOS)
  - c-compiler
  - cxx-compiler
  - fortran-compiler
  - llvm-openmp
  - gsl
  - eigen
  - make
  - compilers 

  # needed because Agama builds via setup.py/pip
  - pkg-config
  - setuptools=<81
  - wheel
  - pip