name: tstrippy
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  # - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  # - ld_impl_linux-64=2.38
  - libffi=3.4.4
  # - libgcc-ng=11.2.0
  # - libgomp=11.2.0
  # - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=23.3.1
  - python=3.11.2
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - alabaster==0.7.16
      - astropy==6.0.0
      - astropy-iers-data==0.2024.1.1.0.33.39
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - defusedxml==0.7.1
      - docutils==0.20.1
      - fastjsonschema==2.19.1
      - h5py==3.10.0
      - idna==3.6
      - imagesize==1.4.1
      - iniconfig==2.0.0
      - jinja2==3.1.3
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-pygments==0.3.0
      - markupsafe==2.1.3
      - mistune==3.0.2
      - nbclient==0.9.0
      - nbconvert==7.14.0
      - nbformat==5.9.2
      - nbsphinx==0.9.3
      - numpy==1.23.0
      - pandocfilters==1.5.0
      - pluggy==1.3.0
      - pyerfa==2.0.1.1
      - pytest==7.4.4
      - pyyaml==6.0.1
      - referencing==0.32.1
      - requests==2.31.0
      - rpds-py==0.16.2
      - snowballstemmer==2.2.0
      - soupsieve==2.5
      - sphinx==7.2.6
      - sphinxcontrib-applehelp==1.0.7
      - sphinxcontrib-devhelp==1.0.5
      - sphinxcontrib-htmlhelp==2.0.4
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.6
      - sphinxcontrib-serializinghtml==1.1.9
      - tinycss2==1.2.1
      - urllib3==2.1.0
      - webencodings==0.5.1
      - tstrippy

