name: tstrippy
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.12
  - numpy>=2.0
  - astropy>=7.0
  - pyyaml>=5.1
  - hdf5
  - pytest
  - meson
  - ninja
  - make
  - pkg-config

  # compiler toolchain (important for Agama + OpenMP on macOS)
  - c-compiler
  - cxx-compiler
  - fortran-compiler
  - llvm-openmp
  - gsl
  - eigen

  # needed because Agama builds via setup.py/pip
  - setuptools
  - wheel
  - pip