name: tstrippy
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.12
  - numpy>=1.20
  - astropy>=4.0
  - pyyaml>=5.1
  - gfortran>=11  # Critical for running the compiled code
  - pip
  - meson 
  - pytest
  # - pip:
    # - git+https://github.com/salvatore-ferrone/tstrippy.git